apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: glooedge-e
  namespace: gloo-system
spec:
  releaseName: glooe
  chart:
    spec:
      chart: gloo-ee
      sourceRef:
        kind: HelmRepository
        name: glooedge-e
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 5 
  values:
    gloo:
      gateway:
        validation:
          allowWarnings: false
          alwaysAcceptResources: false
          disableTransformationValidation: false
          enabled: true
          failurePolicy: Ignore
          secretName: gateway-validation-certs
          serverEnabled: true
          validationServerGrpcMaxSizeBytes: 104857600
          warnRouteShortCircuiting: false
          webhook:
            disableHelmHook: false
            enabled: true
    license_key: "https://lp.solo.io/request-trial"
