apiVersion: v1
kind: Service
metadata:
  name: petclinic-db
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: petclinic-db
  type: ClusterIP
